<?php

use Icinga\Util\Csp;
$style = new \ipl\Web\Style();
$style->setNonce(Csp::getStyleNonce());
$style->add('.leaflet-default-icon-path',['background-image'=>'url(img/map/marker-icon.png)']);
$style->add('.b-width-1px',['border-width'=>'1px']);
$style->add('.map-container',['display'=>'block','width'=>'100%']);
$style->add('.map-home',['height'=>'250px!important','margin-top'=>'0px!important']);
$style->add('.map-home-p',['text-align'=>'right','margin-top'=>'5px','max-width'=>'unset']);


echo $style;
?>

<dt>
    <?= $this->formLabel($this->element->getName(), $this->element->getLabel()); ?>
</dt>
<dd>

    <input id="<?= $this->element->getName(); ?>"
           type="text"
           name="<?= $this->element->getName(); ?>"
           value="<?= $this->element->getValue(); ?>"
        <?php if ($p = $this->element->getAttrib('placeholder')) {
            print 'placeholder="' . htmlspecialchars($p) . '"';
        } ?>/>
    <?php
    if(preg_match("~\(\d+?\)~",$this->element->getLabel()) == false ){?>
        <button type="button" id="director-map-btn-globe" class="control-button b-width-1px">
            <i class="icon-globe"></i>
        </button>
        <div class="container icinga-module module-mapDatatype module-map map-container" data-icinga-module="mapDatatype">

            <div id="map-director" class="map map-home"></div>
            <p class="map-home-p">
                <button type="button" id="director-map-btn-save" class="control-button b-width-1px"">
                    <i class="icon-ok"></i>
                </button>
                <button type="button" id="director-map-btn-cancel" class="control-button b-width-1px">
                    <i class="icon-cancel"></i>
                </button>
            </p>
        </div>


    <?php if (count($this->element->getMessages()) > 0): ?>
        <?= $this->formErrors($this->element->getMessages()); ?>
    <?php endif; ?>

    <?php
    }
    ?>

</dd>
